del fk.h
del fk_define.h
del fk_crypto.hpp
del fk_file.hpp
del fk_inject.hpp
del fk_log.hpp
del fk_string.hpp
del fk_json.hpp
del fk_imgui_impl.hpp
del imconfig.h
del imgui.cpp
del imgui.h
del imgui_demo.cpp
del imgui_draw.cpp
del imgui_internal.h
del imgui_tables.cpp
del imgui_widgets.cpp
del imstb_rectpack.h
del imstb_textedit.h
del imstb_truetype.h
del imgui_impl_dx9.cpp
del imgui_impl_dx9.h
del imgui_impl_win32.cpp
del imgui_impl_win32.h
echo fkø‚«Â¿ÌÕÍ±œ...
pause